name: Superlinter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - run: |
          haxe -version
          haxelib install hxnodejs
