name: Windows Build CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Setup Haxe dependencies
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install flixel-addons
          haxelib git faxe https://github.com/ashea-code/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/Kade-github/extension-webm
          lime rebuild extension-webm windows
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install actuate
          haxelib list
          haxelib run lime build win

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mac Build
          path: export/release/macos/bin
